<a href="https://colab.research.google.com/github/Erick0105/Aula-IA-Fiap/blob/main/An%C3%A1lise_Explorat%C3%B3ria_1_Inicio_de_Aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import das bibliotecas

In [1]:
#import do pandas
import pandas as pd

## Crie um novo dataframe com .csv orders.

In [8]:
#criar novo dataframe a partir de um .csv
df = pd.read_csv("orders.csv")
df.head() # Pega os 5 primeiros, tail os 5 ultimos

,order_id,store_id,channel_id,payment_order_id,delivery_order_id,order_status,order_amount,order_delivery_fee,order_delivery_cost,order_created_hour,...,order_moment_delivering,order_moment_delivered,order_moment_finished,order_metric_collected_time,order_metric_paused_time,order_metric_production_time,order_metric_walking_time,order_metric_expediton_speed_time,order_metric_transit_time,order_metric_cycle_time
368994,93139806,2074,5,93139806,93139806,FINISHED,28.0,0.0,0.00,23,...,5/1/2021 12:44:39 AM,NaN,5/1/2021 1:08:04 AM,0.67,18.33,22.00,4.80,23.13,23.42,68.53
368995,93139809,707,5,93139809,93139809,FINISHED,49.0,11.9,10.04,23,...,5/1/2021 12:36:36 AM,NaN,5/1/2021 12:57:16 AM,1.42,3.48,27.32,6.13,9.62,20.67,57.60
368996,93139813,631,5,93139813,93139813,FINISHED,128.7,11.9,9.29,23,...,5/1/2021 12:47:47 AM,NaN,5/1/2021 1:05:20 AM,11.72,6.38,29.97,11.75,18.13,17.55,65.65
368997,93139814,631,5,93139814,93139814,FINISHED,127.4,11.9,5.00,23,...,5/1/2021 12:31:50 AM,NaN,5/1/2021 12:45:00 AM,NaN,NaN,30.27,NaN,1.88,13.17,45.32
368998,93139817,236,5,93139817,93139817,FINISHED,104.7,11.9,10.67,23,...,5/1/2021 12:26:24 AM,NaN,5/1/2021 12:47:31 AM,NaN,NaN,16.33,NaN,10.27,21.12,47.72

## Quantos registros temos na nossa base?

In [12]:
#quantidade de registros no dataframe
len(df)

368999

## Há dados faltantes na nossa base?

In [13]:
#informações sobre o dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 368999 entries, 0 to 368998
Data columns (total 29 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   order_id                           368999 non-null  int64
 1   store_id                           368999 non-null  int64
 2   channel_id                         368999 non-null  int64
 3   payment_order_id                   368999 non-null  int64
 4   delivery_order_id                  368999 non-null  int64
 5   order_status                       368999 non-null  object
 6   order_amount                       368999 non-null  float64
 7   order_delivery_fee                 368999 non-null  float64
 8   order_delivery_cost                361794 non-null  float64
 9   order_created_hour                 368999 non-null  int64
 10  order_created_minute               368999 non-null  int64
 11  order_created_day                  368999 non-null  int64
 12  order_created_month                368999 non-null  int64
 13  order_created_year                 368999 non-null  int64
 14  order_moment_created               368999 non-null  object
 15  order_moment_accepted              359538 non-null  object
 16  order_moment_ready                 343893 non-null  object
 17  order_moment_collected             326105 non-null  object
 18  order_moment_in_expedition         301570 non-null  object
 19  order_moment_delivering            343683 non-null  object
 20  order_moment_delivered             19601 non-null   object
 21  order_moment_finished              353400 non-null  object
 22  order_metric_collected_time        317507 non-null  float64
 23  order_metric_paused_time           297594 non-null  float64
 24  order_metric_production_time       343892 non-null  float64
 25  order_metric_walking_time          294943 non-null  float64
 26  order_metric_expediton_speed_time  334417 non-null  float64
 27  order_metric_transit_time          343142 non-null  float64
 28  order_metric_cycle_time            353380 non-null  float64
dtypes: float64(10), int64(10), object(9)
memory usage: 81.6+ MB

# Primeira Parte
Ao começar tem que analisar as tabelas e ver os dados faltantes e ver se o tipo de dado Bate

## Desde quando temos esse histórico?

In [14]:
#type da coluna de data
df['order_moment_created'].dtype #Serve para saber o tipo de uma tabela

dtype('O')

In [15]:
#min da coluna de data
df['order_moment_created'].min() #Identifica o Min

'1/1/2021 10:00:35 PM'

In [ ]:
#max da coluna de data
df['order_moment_created'].max() #Identifica o Max

In [ ]:
#Exemplo de format
pd.to_datetime(df['order_moment_created'],format='%m/%d/%yyyy')

In [18]:
#cast da coluna de data para o formato correto
df['order_moment_created'] = pd.to_datetime(df['order_moment_created']) #Transforma em data
#E depois salva e altera apenas em dataframe

In [19]:
#min da coluna de data
df['order_moment_created'].min()

Timestamp('2021-01-01 00:01:36')

In [ ]:
#max da coluna de data
df['order_moment_created'].max()

## Quantas lojas atendemos na nossa base?

In [20]:
#contagem das lojas únicas
len(df['store_id'].unique()) #Unique manda as coisas sem serem repetidas

951

#Importante
É importante analisar os rankings

## Quais são as principais lojas em quantidade de atendimento?

In [21]:
#ranking das maiores lojas por pedidos
df['store_id'].value_counts() #Ve quantas vezes se repete

store_id
53      14004
676     12327
707      9271
149      8110
274      7920
        ...
2317        1
446         1
1123        1
1162        1
2908        1
Name: count, Length: 951, dtype: int64

In [29]:
#group by com contagem agregada #Group by ajuda a fazer a agregação de dados  #Função Agregada
df.groupby(['store_id', 'order_status'])\
  .agg({'order_id':'count'}) \
  .sort_values('order_id',ascending=False) \
  .head()

                       order_id
store_id order_status
53       FINISHED         13903
676      FINISHED         12277
707      FINISHED          9190
149      FINISHED          8013
274      FINISHED          7865

## Qual a distribuição entre os status?

In [26]:
#distribuição entre status
df['order_status'].value_counts()

order_status
FINISHED    352020
CANCELED     16979
Name: count, dtype: int64

In [27]:
#distribuição entre status por porcentagem
df['order_status'].value_counts(normalize=True)

order_status
FINISHED    0.953986
CANCELED    0.046014
Name: proportion, dtype: float64

## Qual o nome das lojas da tabela orders?

In [31]:
#criação de um novo dataframe a partir de stores
df_stores = pd.read_csv('stores.csv',encoding='latin1')
df_stores.head()

,store_id,hub_id,store_name,store_segment,store_plan_price,store_latitude,store_longitude
0,3,2,CUMIURI,FOOD,0.0,NaN,NaN
1,6,3,PIMGUCIS DA VIVA,FOOD,0.0,-30.037415,-51.203520
2,8,3,RASMUR S,FOOD,0.0,-30.037415,-51.203520
3,53,8,PAPA SUCIS,FOOD,0.0,-22.921475,-43.234822
4,54,8,VUZPI PAZZIS,FOOD,0.0,-22.921475,-43.234822

In [32]:
#informações sobre o dataframe
df_stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 951 entries, 0 to 950
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   store_id          951 non-null    int64
 1   hub_id            951 non-null    int64
 2   store_name        951 non-null    object
 3   store_segment     951 non-null    object
 4   store_plan_price  836 non-null    float64
 5   store_latitude    935 non-null    float64
 6   store_longitude   935 non-null    float64
dtypes: float64(3), int64(2), object(2)
memory usage: 52.1+ KB

In [38]:
#criação de um novo dataframe a partir de id e name
df_stores_name = df_stores[['store_id', 'store_name']].copy() #Ele copia para poder fazer uma seleção e armazenar em outra var

In [40]:
#merge/join com orders
df_orders_stores = df.merge(df_stores_name, on=['store_id'], how='left')

In [41]:
#análise dos registros
df_orders_stores.head()

,order_id,store_id,channel_id,payment_order_id,delivery_order_id,order_status,order_amount,order_delivery_fee,order_delivery_cost,order_created_hour,...,order_moment_delivered,order_moment_finished,order_metric_collected_time,order_metric_paused_time,order_metric_production_time,order_metric_walking_time,order_metric_expediton_speed_time,order_metric_transit_time,order_metric_cycle_time,store_name
0,68405119,3512,5,68405119,68405119,CANCELED,62.7,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GOI SIPIMUSU
1,68405123,3512,5,68405123,68405123,CANCELED,62.7,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GOI SIPIMUSU
2,68405206,3512,5,68405206,68405206,CANCELED,115.5,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GOI SIPIMUSU
3,68405465,3401,5,68405465,68405465,CANCELED,55.9,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FRUEOU
4,68406064,3401,5,68406064,68406064,CANCELED,37.9,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FRUEOU

In [42]:
#informações sobre o dataframe
df_orders_stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 368999 entries, 0 to 368998
Data columns (total 30 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   order_id                           368999 non-null  int64
 1   store_id                           368999 non-null  int64
 2   channel_id                         368999 non-null  int64
 3   payment_order_id                   368999 non-null  int64
 4   delivery_order_id                  368999 non-null  int64
 5   order_status                       368999 non-null  object
 6   order_amount                       368999 non-null  float64
 7   order_delivery_fee                 368999 non-null  float64
 8   order_delivery_cost                361794 non-null  float64
 9   order_created_hour                 368999 non-null  int64
 10  order_created_minute               368999 non-null  int64
 11  order_created_day                  368999 non-null  int64
 12  order_created_month                368999 non-null  int64
 13  order_created_year                 368999 non-null  int64
 14  order_moment_created               368999 non-null  datetime64[ns]
 15  order_moment_accepted              359538 non-null  object
 16  order_moment_ready                 343893 non-null  object
 17  order_moment_collected             326105 non-null  object
 18  order_moment_in_expedition         301570 non-null  object
 19  order_moment_delivering            343683 non-null  object
 20  order_moment_delivered             19601 non-null   object
 21  order_moment_finished              353400 non-null  object
 22  order_metric_collected_time        317507 non-null  float64
 23  order_metric_paused_time           297594 non-null  float64
 24  order_metric_production_time       343892 non-null  float64
 25  order_metric_walking_time          294943 non-null  float64
 26  order_metric_expediton_speed_time  334417 non-null  float64
 27  order_metric_transit_time          343142 non-null  float64
 28  order_metric_cycle_time            353380 non-null  float64
 29  store_name                         368999 non-null  object
dtypes: datetime64[ns](1), float64(10), int64(10), object(9)
memory usage: 84.5+ MB

In [47]:
#group by com contagem agregada
df_orders_stores.groupby(['store_name','store_id','order_status'])\
  .agg({'order_id':'count'}) \
  .sort_values('order_id',ascending=False) \
  .head(15)

                                    order_id
store_name   store_id order_status
PAPA SUCIS   53       FINISHED         13903
IUMPICA      676      FINISHED         12277
             707      FINISHED          9190
             149      FINISHED          8013
             274      FINISHED          7865
             658      FINISHED          7361
             236      FINISHED          7241
PAPA SUCIS   294      FINISHED          6884
RC OUMILEES  886      FINISHED          6526
IUMPICA      321      FINISHED          6430
             1037     FINISHED          6112
             495      FINISHED          6095
             631      FINISHED          5219
             416      FINISHED          5181
             496      FINISHED          4938

In [ ]:
#cast como string

In [ ]:
#procura as lojas em stores

In [ ]:
#remove os espaços nas bordas

In [ ]:
#procura as lojas em stores

#Exercícios

## 1 - Quais lojas possuem mais valores repedidos em df_stores?

## 2 - Quais lojas possuem maior valor de pedidos?

## 3 - Quais lojas tem o maior tempo de produção do pedido?

## 4 - Num cenário de negócio, quais alternativas você recomenda para diminuir o tempo de produção dos pedidos?
Pode utilizar o Google, ChatGPT para pesquisar sobre o assunto. Consegue indicar algum artigo ciêntifíco, reposítório, ou análise no Kaggle que já tratou sobre este problema?

## 5 - Quais são os principais Shoppings/Cidades em número de Pedidos. Faça o upload do .csv de hubs e realize os joins entre os dataframes de orders, stores e hubs para chegar no resultado.